# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZTpm6waUcsHce1ZfHgnyH9wtucUYZgYT
"""

#pip install newspaper3k

from textblob import TextBlob
import nltk
from newspaper import Article

url = 'https://futurism.com/the-byte/darpa-officially-studying-combat-jetpacks-military'
article = Article(url)

#NLP
article.download()
article.parse()
nltk.download('punkt')
article.nlp()

text = article.summary
print(text)

obj = TextBlob(text)

# sentiment value between -1 and 1
sentiment = obj.sentiment.polarity
print(sentiment)

if sentiment > 0.4:
  print('The text is positive')
elif sentiment < -0.4:
  print('The text is negative')
else:
  print('The text is neutral')
